
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/nix/store/01dapiw4pjrc9s0166dcyg9xkw0rv01z-cmake-3.31.5/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "/home/reima/zmk-workspace/zephyr/cmake/modules/kernel.cmake:128 (project)"
      - "/home/reima/zmk-workspace/zephyr/cmake/modules/zephyr_default.cmake:138 (include)"
      - "/home/reima/zmk-workspace/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/reima/zmk-workspace/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:9 (find_package)"
    message: |
      The target system is: Generic - 3.5.0 - arm
      The host system is: Linux - 5.15.167.4-microsoft-standard-WSL2 - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/nix/store/01dapiw4pjrc9s0166dcyg9xkw0rv01z-cmake-3.31.5/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/nix/store/01dapiw4pjrc9s0166dcyg9xkw0rv01z-cmake-3.31.5/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/nix/store/01dapiw4pjrc9s0166dcyg9xkw0rv01z-cmake-3.31.5/share/cmake-3.31/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "/home/reima/zmk-workspace/zephyr/cmake/modules/kernel.cmake:128 (project)"
      - "/home/reima/zmk-workspace/zephyr/cmake/modules/zephyr_default.cmake:138 (include)"
      - "/home/reima/zmk-workspace/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/reima/zmk-workspace/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:9 (find_package)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /nix/store/4viqyxy7nfd3nxw9zcqxy1j6gqcbg2lc-zephyr-sdk-0.16.9/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc 
      Build flags: 
      Id flags:  
      
      The output was:
      1
      /nix/store/4viqyxy7nfd3nxw9zcqxy1j6gqcbg2lc-zephyr-sdk-0.16.9/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld: /nix/store/4viqyxy7nfd3nxw9zcqxy1j6gqcbg2lc-zephyr-sdk-0.16.9/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/lib/libc.a(lib_a-exit.o): in function `exit':
      exit.c:(.text.exit+0x34): undefined reference to `_exit'
      collect2: error: ld returned 1 exit status
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/nix/store/01dapiw4pjrc9s0166dcyg9xkw0rv01z-cmake-3.31.5/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/nix/store/01dapiw4pjrc9s0166dcyg9xkw0rv01z-cmake-3.31.5/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/nix/store/01dapiw4pjrc9s0166dcyg9xkw0rv01z-cmake-3.31.5/share/cmake-3.31/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "/home/reima/zmk-workspace/zephyr/cmake/modules/kernel.cmake:128 (project)"
      - "/home/reima/zmk-workspace/zephyr/cmake/modules/zephyr_default.cmake:138 (include)"
      - "/home/reima/zmk-workspace/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/reima/zmk-workspace/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:9 (find_package)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /nix/store/4viqyxy7nfd3nxw9zcqxy1j6gqcbg2lc-zephyr-sdk-0.16.9/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc 
      Build flags: 
      Id flags: -c 
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.o"
      
      The C compiler identification is GNU, found in:
        /home/reima/zmk-workspace/.build/aeonclok_left-nice_nano_v2/CMakeFiles/3.31.5/CompilerIdC/CMakeCCompilerId.o
      
  -
    kind: "message-v1"
    backtrace:
      - "/nix/store/01dapiw4pjrc9s0166dcyg9xkw0rv01z-cmake-3.31.5/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/nix/store/01dapiw4pjrc9s0166dcyg9xkw0rv01z-cmake-3.31.5/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/nix/store/01dapiw4pjrc9s0166dcyg9xkw0rv01z-cmake-3.31.5/share/cmake-3.31/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "/home/reima/zmk-workspace/zephyr/cmake/modules/kernel.cmake:128 (project)"
      - "/home/reima/zmk-workspace/zephyr/cmake/modules/zephyr_default.cmake:138 (include)"
      - "/home/reima/zmk-workspace/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/reima/zmk-workspace/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:9 (find_package)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler: /nix/store/4viqyxy7nfd3nxw9zcqxy1j6gqcbg2lc-zephyr-sdk-0.16.9/arm-zephyr-eabi/bin/arm-zephyr-eabi-g++ 
      Build flags: 
      Id flags:  
      
      The output was:
      1
      /nix/store/4viqyxy7nfd3nxw9zcqxy1j6gqcbg2lc-zephyr-sdk-0.16.9/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld: /nix/store/4viqyxy7nfd3nxw9zcqxy1j6gqcbg2lc-zephyr-sdk-0.16.9/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/lib/libc.a(lib_a-exit.o): in function `exit':
      exit.c:(.text.exit+0x34): undefined reference to `_exit'
      collect2: error: ld returned 1 exit status
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/nix/store/01dapiw4pjrc9s0166dcyg9xkw0rv01z-cmake-3.31.5/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/nix/store/01dapiw4pjrc9s0166dcyg9xkw0rv01z-cmake-3.31.5/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/nix/store/01dapiw4pjrc9s0166dcyg9xkw0rv01z-cmake-3.31.5/share/cmake-3.31/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "/home/reima/zmk-workspace/zephyr/cmake/modules/kernel.cmake:128 (project)"
      - "/home/reima/zmk-workspace/zephyr/cmake/modules/zephyr_default.cmake:138 (include)"
      - "/home/reima/zmk-workspace/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/reima/zmk-workspace/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:9 (find_package)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: /nix/store/4viqyxy7nfd3nxw9zcqxy1j6gqcbg2lc-zephyr-sdk-0.16.9/arm-zephyr-eabi/bin/arm-zephyr-eabi-g++ 
      Build flags: 
      Id flags: -c 
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.o"
      
      The CXX compiler identification is GNU, found in:
        /home/reima/zmk-workspace/.build/aeonclok_left-nice_nano_v2/CMakeFiles/3.31.5/CompilerIdCXX/CMakeCXXCompilerId.o
      
  -
    kind: "message-v1"
    backtrace:
      - "/nix/store/01dapiw4pjrc9s0166dcyg9xkw0rv01z-cmake-3.31.5/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:1237 (message)"
      - "/nix/store/01dapiw4pjrc9s0166dcyg9xkw0rv01z-cmake-3.31.5/share/cmake-3.31/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "/home/reima/zmk-workspace/zephyr/cmake/modules/kernel.cmake:134 (enable_language)"
      - "/home/reima/zmk-workspace/zephyr/cmake/modules/zephyr_default.cmake:138 (include)"
      - "/home/reima/zmk-workspace/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/reima/zmk-workspace/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:9 (find_package)"
    message: |
      Checking whether the ASM compiler is GNU using "--version" matched "(GNU assembler)|(GCC)|(Free Software Foundation)":
      arm-zephyr-eabi-gcc (Zephyr SDK 0.16.9) 12.2.0
      Copyright (C) 2022 Free Software Foundation, Inc.
      This is free software; see the source for copying conditions.  There is NO
      warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
      
...
